# source - https://github.com/Platane/Platane/blob/master/.github/workflows/main.yml#L26-L33
name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate snake svg
        uses: Platane/snk/@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # color_dots:  The first one is 0 contribution, then it goes from the low contribution to the highest.
          #              Exactly 5 colors are expected.
          outputs: |
            dist/snake.svg?color_snake=#707070&color_dots=#eaeaea,#5d5d5d,#4e4e4e,#414141,#353535
            dist/snake-dark.svg?color_snake=#707070&color_dots=#1e1e1e,#878787,#9d9d9d,#b3b3b3,#cccccc

      # push the content of <build_dir> to a branch
      # access pushed content at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
