# reference: https://github.com/x0rzavi/x0rzavi
name: generate terminal animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install git+https://github.com/x0rzavi/github-readme-terminal.git@main

      - name: Run python script to generate output gif
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMGBB_API_KEY: ${{ secrets.IMGBB_API_KEY }}
          GIFOS_GENERAL_FPS: 13
          GIFOS_GENERAL_LOOP_COUNT: 4
          GIFOS_GENERAL_COLOR_SCHEME: "everblush"

      - name: Create dist directory
        run: mkdir -p dist

      - name: Copy gif to dist
        run: cp output.gif dist/

      - name: Push output gif to terminal branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: terminal
          build_dir: dist
          # keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
